import {
  Armchair,
  Baby,
  BookOpen,
  Camera,
  Car,
  Dog,
  Dumbbell,
  Gamepad2,
  Gem,
  Hammer,
  Heart,
  Laptop,
  Bike,
  type LucideIcon,
  Monitor,
  MonitorSmartphone,
  Music,
  Package2,
  PackageOpen,
  Repeat2,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sofa,
  Sparkles,
  Trophy,
  Wrench,
  WashingMachine,
  Watch,
  Briefcase,
} from "lucide-react";

/** Maps a category `icon` key (see @swap/config categories) to a Lucide icon. */
const ICON_MAP: Record<string, LucideIcon> = {
  electronics: MonitorSmartphone,
  mobiles: Smartphone,
  computers: Laptop,
  gaming: Gamepad2,
  appliances: WashingMachine,
  furniture: Armchair,
  "home-garden": Sofa,
  cars: Car,
  motorcycles: Bike,
  "auto-parts": Wrench,
  fashion: Shirt,
  watches: Watch,
  baby: Baby,
  toys: Trophy,
  sports: Dumbbell,
  books: BookOpen,
  tools: Hammer,
  health: Heart,
  pets: Dog,
  music: Music,
  cameras: Camera,
  materials: Package2,
  office: Briefcase,
  collectibles: Gem,
  "open-exchange": Repeat2,
  other: ShoppingBag,
  // legacy / misc fallbacks
  jewelry: Sparkles,
  monitor: Monitor,
  open: PackageOpen,
};

export function CategoryIcon({ icon, className }: { icon: string; className?: string }) {
  const Icon = ICON_MAP[icon] ?? ShoppingBag;
  return <Icon className={className} aria-hidden strokeWidth={2} />;
}
